'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5448
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ConMO
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="SmartMOStr", [Namespace]:="http://tempuri.org/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class SmartMOStr
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MSISDNField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ShortCodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MessageField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TransactionIDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ServiceIDField As String
        
        Private TelcoIDField As Integer
        
        Private ReceiveDateField As Date
        
        Private RetryCountField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property MSISDN() As String
            Get
                Return Me.MSISDNField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MSISDNField, value) <> true) Then
                    Me.MSISDNField = value
                    Me.RaisePropertyChanged("MSISDN")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ShortCode() As String
            Get
                Return Me.ShortCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ShortCodeField, value) <> true) Then
                    Me.ShortCodeField = value
                    Me.RaisePropertyChanged("ShortCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property Message() As String
            Get
                Return Me.MessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MessageField, value) <> true) Then
                    Me.MessageField = value
                    Me.RaisePropertyChanged("Message")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property TransactionID() As String
            Get
                Return Me.TransactionIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TransactionIDField, value) <> true) Then
                    Me.TransactionIDField = value
                    Me.RaisePropertyChanged("TransactionID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public Property ServiceID() As String
            Get
                Return Me.ServiceIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ServiceIDField, value) <> true) Then
                    Me.ServiceIDField = value
                    Me.RaisePropertyChanged("ServiceID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=5)>  _
        Public Property TelcoID() As Integer
            Get
                Return Me.TelcoIDField
            End Get
            Set
                If (Me.TelcoIDField.Equals(value) <> true) Then
                    Me.TelcoIDField = value
                    Me.RaisePropertyChanged("TelcoID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=6)>  _
        Public Property ReceiveDate() As Date
            Get
                Return Me.ReceiveDateField
            End Get
            Set
                If (Me.ReceiveDateField.Equals(value) <> true) Then
                    Me.ReceiveDateField = value
                    Me.RaisePropertyChanged("ReceiveDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=7)>  _
        Public Property RetryCount() As Integer
            Get
                Return Me.RetryCountField
            End Get
            Set
                If (Me.RetryCountField.Equals(value) <> true) Then
                    Me.RetryCountField = value
                    Me.RaisePropertyChanged("RetryCount")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ConMO.IMO")>  _
    Public Interface IMO
        
        'CODEGEN: Generating message contract since element name body from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(IsOneWay:=true, Action:="http://tempuri.org/IMO/PostSmartMO")>  _
        Sub PostSmartMO(ByVal request As ConMO.PostSmartMO)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class PostSmartMO
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="PostSmartMO", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ConMO.PostSmartMOBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ConMO.PostSmartMOBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class PostSmartMOBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public body As ConMO.SmartMOStr
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal body As ConMO.SmartMOStr)
            MyBase.New
            Me.body = body
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface IMOChannel
        Inherits ConMO.IMO, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class MOClient
        Inherits System.ServiceModel.ClientBase(Of ConMO.IMO)
        Implements ConMO.IMO
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Sub ConMO_IMO_PostSmartMO(ByVal request As ConMO.PostSmartMO) Implements ConMO.IMO.PostSmartMO
            MyBase.Channel.PostSmartMO(request)
        End Sub
        
        Public Sub PostSmartMO(ByVal body As ConMO.SmartMOStr)
            Dim inValue As ConMO.PostSmartMO = New ConMO.PostSmartMO
            inValue.Body = New ConMO.PostSmartMOBody
            inValue.Body.body = body
            CType(Me,ConMO.IMO).PostSmartMO(inValue)
        End Sub
    End Class
End Namespace
