'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4984
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4984.
'
Namespace ConMO
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="BasicHttpBinding_IMO", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ConMO
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private PostSmartMOOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.SmartAWSReceive.My.MySettings.Default.SmartMOReceive_ConMO_ConMO
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event PostSmartMOCompleted As PostSmartMOCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMO/PostSmartMO", RequestNamespace:="http://tempuri.org/", OneWay:=true, Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub PostSmartMO(ByVal body As SmartMOStr)
            Me.Invoke("PostSmartMO", New Object() {body})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub PostSmartMOAsync(ByVal body As SmartMOStr)
            Me.PostSmartMOAsync(body, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub PostSmartMOAsync(ByVal body As SmartMOStr, ByVal userState As Object)
            If (Me.PostSmartMOOperationCompleted Is Nothing) Then
                Me.PostSmartMOOperationCompleted = AddressOf Me.OnPostSmartMOOperationCompleted
            End If
            Me.InvokeAsync("PostSmartMO", New Object() {body}, Me.PostSmartMOOperationCompleted, userState)
        End Sub
        
        Private Sub OnPostSmartMOOperationCompleted(ByVal arg As Object)
            If (Not (Me.PostSmartMOCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent PostSmartMOCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SmartMOStr
        
        Private mSISDNField As String
        
        Private shortCodeField As String
        
        Private messageField As String
        
        Private transactionIDField As String
        
        Private serviceIDField As String
        
        Private telcoIDField As Integer
        
        Private receiveDateField As Date
        
        Private retryCountField As Integer
        
        '''<remarks/>
        Public Property MSISDN() As String
            Get
                Return Me.mSISDNField
            End Get
            Set
                Me.mSISDNField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ShortCode() As String
            Get
                Return Me.shortCodeField
            End Get
            Set
                Me.shortCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TransactionID() As String
            Get
                Return Me.transactionIDField
            End Get
            Set
                Me.transactionIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ServiceID() As String
            Get
                Return Me.serviceIDField
            End Get
            Set
                Me.serviceIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TelcoID() As Integer
            Get
                Return Me.telcoIDField
            End Get
            Set
                Me.telcoIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ReceiveDate() As Date
            Get
                Return Me.receiveDateField
            End Get
            Set
                Me.receiveDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RetryCount() As Integer
            Get
                Return Me.retryCountField
            End Get
            Set
                Me.retryCountField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")>  _
    Public Delegate Sub PostSmartMOCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
End Namespace
